### ISSUE TITLE
NtpServerInterval flags defined incorrectly in Get-TimeSetttings

### ISSUE THREAD

**Issue by rmbolger** [EvotecIT/PSSharedGoods#23] opened 2021-06-30 23:47 UTC
According to the [NtpServer doc reference](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings#parameters), the flags that can be associated with external NTP servers are:

> 0x01 SpecialInterval
0x02 UseAsFallbackOnly
0x04 SymmetricActive: For more information about this mode, see Windows Time Server.
0x08 Client

But the code defines them without the appropriate leading zero which breaks the string matching later in the function.

https://github.com/EvotecIT/PSSharedGoods/blob/0014318fe54dee902cffbab599805025719d38d0/Public/Time/Get-TimeSettings.ps1#L85-L91

So if NtpServer is set to a value like `0.pool.ntp.org,0x08 1.pool.ntp.org,0x08`, it shows up as `NtpServerIntervals : {Incorrect, Incorrect}` instead of `NtpServerIntervals : {Client, Client}` in the function output.

As a tangential issue, these are bit flags that can be combined. So you may want to either change the code to interpret them as such, or include all combinations of the flags in the `$NtpServerInterval` definition like this:

```
$NtpServerIntervals = @{
    '0x01' = 'SpecialInterval'
    '0x02' = 'UseAsFallbackOnly'
    '0x03' = 'SpecialInterval+UseAsFallbackOnly'
    '0x04' = 'SymmetricActive'
    '0x05' = 'SpecialInterval+SymmetricActive'
    '0x06' = 'UseAsFallbackOnly+SymmetricActive'
    '0x07' = 'SpecialInterval+UseAsFallbackOnly+SymmetricActive'
    '0x08' = 'Client'
    '0x09' = 'SpecialInterval+Client'
    '0x0A' = 'UseAsFallbackOnly+Client'
    '0x0B' = 'SpecialInterval+UseAsFallbackOnly+Client'
    '0x0C' = 'SymmetricActive+Client'
    '0x0D' = 'SpecialInterval+SymmetricActive+Client'
    '0x0E' = 'UseAsFallbackOnly+SymmetricActive+Client'
    '0x0F' = 'SpecialInterval+UseAsFallbackOnly+SymmetricActive+Client'
}
```

**Comment by PrzemyslawKlys** [comment] 2021-07-03 06:40
Thank you for reporting this. I guess the problem is - it works on my machine. So it needs to be fixed with both options in mind 0x01 and 0x1

```powershell
Get-PSRegistry -ComputerName $_ -RegistryPath "HKLM\SYSTEM\CurrentControlSet\Services\W32Time\Parameters"
```

On my Windows 10 machine (as coming from Microsoft)

![image](https://user-images.githubusercontent.com/15063294/124345553-e3bafa00-dbd9-11eb-94f7-afd5650979ce.png)

On my AD

![image](https://user-images.githubusercontent.com/15063294/124345578-064d1300-dbda-11eb-8a08-1d57a23969bf.png)

On my AD2

![image](https://user-images.githubusercontent.com/15063294/124345590-18c74c80-dbda-11eb-8cb2-1d4c64a01373.png)

So, the logic based on your documentation + feedback would need to allow for both. Care for a PR?

**Comment by rmbolger** [comment] 2021-07-03 16:21
Huh, that's good to know for future reference. Apparently it's trailing zeros that matter rather than leading zeroes. At least from a PowerShell perspective, `0x1` and `0x01` are both interpreted as 1. But `0x10` is interpreted as 16.

That probably means the best solution is to go the interpreting route rather than the string matching route. I'll mess around with it and see if I can come up with something if I can find some more time.

**Comment by PrzemyslawKlys** [comment] 2021-07-04 08:02
Thank you for your help ;)

**Closed as completed by PrzemyslawKlys** 2021-07-04 08:02 UTC
